"""Themes (v1.0.0, step 3). No display needed."""

from __future__ import annotations

import sys
import tempfile
import tomllib
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from alacrittyforge import themes  # noqa: E402
from alacrittyforge.session import Session  # noqa: E402
from alacrittyforge.settings_file import REMOVE  # noqa: E402

KOGNOG = '''[colors.primary]
background = "#1a1a1a"
foreground = "#cdd6f4"

[colors.normal]
red = "#f38ba8"
'''
HYPE = '''# Generated by hypeForge: the Catppuccin Mocha theme's terminal colours (D-36, F-12).
# Do not edit; it is rewritten from themes/terminal.lua.

[colors.primary]
background = "#1e1e2e"
'''


class Case(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.home = Path(self._tmp.name)
        self.tdir = self.home / "themes"
        self.tdir.mkdir()
        (self.tdir / "KognogOS-theme.toml").write_text(KOGNOG)
        (self.tdir / "hypeforge-mocha.toml").write_text(HYPE)
        (self.tdir / "broken.toml").write_text("[colors\n")
        self.cfg = self.home / "alacritty.toml"
        self.cfg.write_text(f'[general]\nimport = ["{self.tdir}/KognogOS-theme.toml", "{self.home}/extra.toml"]\n'
                            '\n[colors.primary]\nbackground = "#000000"\n')
        self.s = Session.load(self.cfg, backup_dir=self.home / "bk")

    def tearDown(self):
        self._tmp.cleanup()


class Listing(Case):
    def test_themes_are_listed_with_hypeforges_locked(self):
        ts = {t.name: t for t in themes.list_themes(self.tdir)}
        self.assertEqual(sorted(ts, key=str.lower), ["broken", "hypeforge-mocha", "KognogOS-theme"])
        self.assertEqual(ts["hypeforge-mocha"].locked_by, "hypeForge")
        self.assertFalse(ts["KognogOS-theme"].locked)
        self.assertTrue(ts["broken"].error)
        self.assertEqual(ts["KognogOS-theme"].colour("primary.background"), "#1a1a1a")
        self.assertEqual(ts["KognogOS-theme"].shown("normal.green"), themes.DEFAULTS["normal.green"])

    def test_the_theme_in_use_is_found(self):
        self.assertEqual(themes.active_theme(self.s, self.tdir), self.tdir / "KognogOS-theme.toml")
        self.assertEqual(themes.own_colours(self.s), {"primary": {"background": "#000000"}})


class Using(Case):
    def test_using_a_theme_keeps_other_imports_and_takes_own_colours_out(self):
        ch = themes.use_changes(self.s, self.tdir / "hypeforge-mocha.toml", self.tdir)
        self.assertEqual(ch["general.import"][0], themes.import_path(self.tdir / "hypeforge-mocha.toml"))
        self.assertIn(f"{self.home}/extra.toml", ch["general.import"])
        self.assertNotIn(f"{self.tdir}/KognogOS-theme.toml", ch["general.import"])
        self.assertIs(ch["colors"], REMOVE)

    def test_the_review_says_it_in_words(self):
        for k, v in themes.use_changes(self.s, self.tdir / "hypeforge-mocha.toml", self.tdir).items():
            self.s.pending[k] = v
        rows = dict((label, (old, new)) for label, old, new in self.s.changes())
        self.assertEqual(rows["Theme"], ("KognogOS-theme", "hypeforge-mocha"))
        self.assertIn("taken out", rows["Your own colours (in the settings file)"][1])

    def test_a_locked_file_is_never_written(self):
        before = (self.tdir / "hypeforge-mocha.toml").read_text()
        for k, v in themes.use_changes(self.s, self.tdir / "hypeforge-mocha.toml", self.tdir).items():
            self.s.pending[k] = v
        self.s.save()
        self.assertEqual((self.tdir / "hypeforge-mocha.toml").read_text(), before)
        data = tomllib.loads(self.cfg.read_text())
        self.assertNotIn("colors", data)


class NewThemes(Case):
    def test_a_copy_gets_a_free_name_and_valid_text(self):
        (self.tdir / "KognogOS-theme (mine).toml").write_text(KOGNOG)
        name = themes.free_name("KognogOS-theme", self.tdir)
        self.assertEqual(name, "KognogOS-theme (mine 2)")
        text = themes.theme_text({"primary": {"background": "#101010"}}, "KognogOS-theme")
        self.assertEqual(tomllib.loads(text), {"colors": {"primary": {"background": "#101010"}}})

    def test_a_new_theme_waits_for_save_and_never_overwrites(self):
        new = self.tdir / "mine.toml"
        self.s.add_file(new, themes.theme_text({"primary": {"background": "#101010"}}))
        self.assertFalse(new.exists())                      # nothing written yet
        self.assertEqual(self.s.change_count, 1)
        self.s.save()
        self.assertTrue(new.exists())
        self.s.add_file(new, "x")
        with self.assertRaises(FileExistsError):
            self.s.save()
        self.assertNotEqual(new.read_text(), "x")

    def test_install_refuses_what_isnt_a_colour_theme(self):
        ok = self.home / "dracula.toml"
        ok.write_text(KOGNOG)
        self.assertEqual(themes.check_install(ok), "")
        sneaky = self.home / "sneaky.toml"
        sneaky.write_text(KOGNOG + '\n[terminal.shell]\nprogram = "/tmp/evil"\n')
        self.assertIn("more than colours", themes.check_install(sneaky))
        plain = self.home / "plain.toml"
        plain.write_text("[window]\nopacity = 0.5\n")
        self.assertIn("no colours", themes.check_install(plain))
        self.assertIn("can't be read", themes.check_install(self.tdir / "broken.toml"))
        (self.home / "notes.txt").write_text("hi")
        self.assertIn(".toml", themes.check_install(self.home / "notes.txt"))

    def test_a_name_becomes_a_safe_file_name(self):
        self.assertEqual(themes.safe_file_name("../../etc/passwd"), "etcpasswd")
        self.assertEqual(themes.safe_file_name("My theme (2)"), "My theme (2)")


if __name__ == "__main__":
    unittest.main()
