"""Alacritty's own keyboard shortcuts on Linux (v1.0.0).

Extracted from Alacritty 0.17.0's manual page, alacritty-bindings(5): the
shortcuts for every system, the Windows/Linux/BSD ones, and the vi-mode and
search-mode ones (macOS-only and Windows-only left out). Generated; don't edit.
"""

DEFAULTS = [
    {'key': 'Paste', 'action': 'Paste', 'group': 'general'},
    {'key': 'Copy', 'action': 'Copy', 'group': 'general'},
    {'key': 'L', 'mods': 'Control', 'action': 'ClearLogNotice', 'group': 'general'},
    {'key': 'Paste', 'mode': 'Vi|Search', 'action': 'Paste', 'group': 'general'},
    {'key': 'L', 'mods': 'Control', 'mode': '~Vi|~Search', 'chars': '\x0c', 'group': 'general'},
    {'key': 'PageUp', 'mods': 'Shift', 'mode': '~Alt', 'action': 'ScrollPageUp', 'group': 'general'},
    {'key': 'PageDown', 'mods': 'Shift', 'mode': '~Alt', 'action': 'ScrollPageDown', 'group': 'general'},
    {'key': 'Home', 'mods': 'Shift', 'mode': '~Alt', 'action': 'ScrollToTop', 'group': 'general'},
    {'key': 'End', 'mods': 'Shift', 'mode': '~Alt', 'action': 'ScrollToBottom', 'group': 'general'},
    {'key': 'Space', 'mods': 'Shift|Control', 'mode': '~Search', 'action': 'ToggleViMode', 'group': 'vi'},
    {'key': 'Space', 'mods': 'Shift|Control', 'mode': 'Vi|~Search', 'action': 'ScrollToBottom', 'group': 'vi'},
    {'key': 'Escape', 'mode': 'Vi|~Search', 'action': 'ClearSelection', 'group': 'vi'},
    {'key': 'I', 'mode': 'Vi|~Search', 'action': 'ToggleViMode', 'group': 'vi'},
    {'key': 'I', 'mode': 'Vi|~Search', 'action': 'ScrollToBottom', 'group': 'vi'},
    {'key': 'C', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ToggleViMode', 'group': 'vi'},
    {'key': 'Y', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollLineUp', 'group': 'vi'},
    {'key': 'E', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollLineDown', 'group': 'vi'},
    {'key': 'G', 'mode': 'Vi|~Search', 'action': 'ScrollToTop', 'group': 'vi'},
    {'key': 'G', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ScrollToBottom', 'group': 'vi'},
    {'key': 'B', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollPageUp', 'group': 'vi'},
    {'key': 'F', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollPageDown', 'group': 'vi'},
    {'key': 'U', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollHalfPageUp', 'group': 'vi'},
    {'key': 'D', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ScrollHalfPageDown', 'group': 'vi'},
    {'key': 'Y', 'mode': 'Vi|~Search', 'action': 'Copy', 'group': 'vi'},
    {'key': 'Y', 'mode': 'Vi|~Search', 'action': 'ClearSelection', 'group': 'vi'},
    {'key': 'Copy', 'mode': 'Vi|~Search', 'action': 'ClearSelection', 'group': 'vi'},
    {'key': 'Y', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ToggleNormalSelection', 'group': 'vi'},
    {'key': 'Y', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Last', 'group': 'vi'},
    {'key': 'Y', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Copy', 'group': 'vi'},
    {'key': 'Y', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ClearSelection', 'group': 'vi'},
    {'key': 'V', 'mode': 'Vi|~Search', 'action': 'ToggleNormalSelection', 'group': 'vi'},
    {'key': 'V', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ToggleLineSelection', 'group': 'vi'},
    {'key': 'V', 'mods': 'Control', 'mode': 'Vi|~Search', 'action': 'ToggleBlockSelection', 'group': 'vi'},
    {'key': 'V', 'mods': 'Alt', 'mode': 'Vi|~Search', 'action': 'ToggleSemanticSelection', 'group': 'vi'},
    {'key': 'Enter', 'mode': 'Vi|~Search', 'action': 'Open', 'group': 'vi'},
    {'key': 'Z', 'mode': 'Vi|~Search', 'action': 'CenterAroundViCursor', 'group': 'vi'},
    {'key': 'F', 'mode': 'Vi|~Search', 'action': 'InlineSearchForward', 'group': 'vi'},
    {'key': 'F', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'InlineSearchBackward', 'group': 'vi'},
    {'key': 'T', 'mode': 'Vi|~Search', 'action': 'InlineSearchForwardShort', 'group': 'vi'},
    {'key': 'T', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'InlineSearchBackwardShort', 'group': 'vi'},
    {'key': ';', 'mode': 'Vi|~Search', 'action': 'InlineSearchNext', 'group': 'vi'},
    {'key': ',', 'mode': 'Vi|~Search', 'action': 'InlineSearchPrevious', 'group': 'vi'},
    {'key': '*', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'SemanticSearchForward', 'group': 'vi'},
    {'key': '#', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'SemanticSearchBackward', 'group': 'vi'},
    {'key': 'K', 'mode': 'Vi|~Search', 'action': 'Up', 'group': 'vi'},
    {'key': 'J', 'mode': 'Vi|~Search', 'action': 'Down', 'group': 'vi'},
    {'key': 'H', 'mode': 'Vi|~Search', 'action': 'Left', 'group': 'vi'},
    {'key': 'L', 'mode': 'Vi|~Search', 'action': 'Right', 'group': 'vi'},
    {'key': 'ArrowUp', 'mode': 'Vi|~Search', 'action': 'Up', 'group': 'vi'},
    {'key': 'ArrowDown', 'mode': 'Vi|~Search', 'action': 'Down', 'group': 'vi'},
    {'key': 'ArrowLeft', 'mode': 'Vi|~Search', 'action': 'Left', 'group': 'vi'},
    {'key': 'ArrowRight', 'mode': 'Vi|~Search', 'action': 'Right', 'group': 'vi'},
    {'key': '0', 'mode': 'Vi|~Search', 'action': 'First', 'group': 'vi'},
    {'key': '$', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Last', 'group': 'vi'},
    {'key': 'Home', 'mode': 'Vi|~Search', 'action': 'First', 'group': 'vi'},
    {'key': 'End', 'mode': 'Vi|~Search', 'action': 'Last', 'group': 'vi'},
    {'key': '^', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'FirstOccupied', 'group': 'vi'},
    {'key': 'H', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'High', 'group': 'vi'},
    {'key': 'M', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Middle', 'group': 'vi'},
    {'key': 'L', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Low', 'group': 'vi'},
    {'key': 'B', 'mode': 'Vi|~Search', 'action': 'SemanticLeft', 'group': 'vi'},
    {'key': 'W', 'mode': 'Vi|~Search', 'action': 'SemanticRight', 'group': 'vi'},
    {'key': 'E', 'mode': 'Vi|~Search', 'action': 'SemanticRightEnd', 'group': 'vi'},
    {'key': 'B', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'WordLeft', 'group': 'vi'},
    {'key': 'W', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'WordRight', 'group': 'vi'},
    {'key': 'E', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'WordRightEnd', 'group': 'vi'},
    {'key': '%', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'Bracket', 'group': 'vi'},
    {'key': '{', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ParagraphUp', 'group': 'vi'},
    {'key': '}', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'ParagraphDown', 'group': 'vi'},
    {'key': '/', 'mode': 'Vi|~Search', 'action': 'SearchForward', 'group': 'vi'},
    {'key': '?', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'SearchBackward', 'group': 'vi'},
    {'key': 'N', 'mode': 'Vi|~Search', 'action': 'SearchNext', 'group': 'vi'},
    {'key': 'N', 'mods': 'Shift', 'mode': 'Vi|~Search', 'action': 'SearchPrevious', 'group': 'vi'},
    {'key': 'Enter', 'mode': 'Search|Vi', 'action': 'SearchConfirm', 'group': 'search'},
    {'key': 'Escape', 'mode': 'Search', 'action': 'SearchCancel', 'group': 'search'},
    {'key': 'C', 'mods': 'Control', 'mode': 'Search', 'action': 'SearchCancel', 'group': 'search'},
    {'key': 'U', 'mods': 'Control', 'mode': 'Search', 'action': 'SearchClear', 'group': 'search'},
    {'key': 'W', 'mods': 'Control', 'mode': 'Search', 'action': 'SearchDeleteWord', 'group': 'search'},
    {'key': 'P', 'mods': 'Control', 'mode': 'Search', 'action': 'SearchHistoryPrevious', 'group': 'search'},
    {'key': 'N', 'mods': 'Control', 'mode': 'Search', 'action': 'SearchHistoryNext', 'group': 'search'},
    {'key': 'ArrowUp', 'mode': 'Search', 'action': 'SearchHistoryPrevious', 'group': 'search'},
    {'key': 'ArrowDown', 'mode': 'Search', 'action': 'SearchHistoryNext', 'group': 'search'},
    {'key': 'Enter', 'mode': 'Search|~Vi', 'action': 'SearchFocusNext', 'group': 'search'},
    {'key': 'V', 'mods': 'Control|Shift', 'mode': '~Vi', 'action': 'Paste', 'group': 'general'},
    {'key': 'V', 'mods': 'Control|Shift', 'mode': 'Vi|Search', 'action': 'Paste', 'group': 'general'},
    {'key': 'C', 'mods': 'Control|Shift', 'action': 'Copy', 'group': 'general'},
    {'key': 'F', 'mods': 'Control|Shift', 'mode': '~Search', 'action': 'SearchForward', 'group': 'general'},
    {'key': 'B', 'mods': 'Control|Shift', 'mode': '~Search', 'action': 'SearchBackward', 'group': 'general'},
    {'key': 'C', 'mods': 'Control|Shift', 'mode': 'Vi|~Search', 'action': 'ClearSelection', 'group': 'general'},
    {'key': 'Insert', 'mods': 'Shift', 'action': 'PasteSelection', 'group': 'general'},
    {'key': '0', 'mods': 'Control', 'action': 'ResetFontSize', 'group': 'general'},
    {'key': '=', 'mods': 'Control', 'action': 'IncreaseFontSize', 'group': 'general'},
    {'key': '+', 'mods': 'Control', 'action': 'IncreaseFontSize', 'group': 'general'},
    {'key': 'NumpadAdd', 'mods': 'Control', 'action': 'IncreaseFontSize', 'group': 'general'},
    {'key': '-', 'mods': 'Control', 'action': 'DecreaseFontSize', 'group': 'general'},
    {'key': 'NumpadSubtract', 'mods': 'Control', 'action': 'DecreaseFontSize', 'group': 'general'},
]
