"""Themes: colour files in ~/.config/alacritty/themes (v1.0.0).

Alacritty can be themed two ways, and alacrittyForge handles both:
- **a theme file**, named in ``general.import``; the settings file's own
  ``[colors]``, if any, win over it (the importing file is applied last);
- **colours in the settings file itself** (``[colors]``), shown as "My colours".

Using a theme puts it first in ``general.import`` (other imports stay) and
takes the settings file's own colours out, because they would hide it; the
review says so, and a backup is made. Files another tool maintains (hypeForge
writes "Do not edit; it is rewritten") are **locked**: listed and usable,
never written. New theme files (Adjust colours, Save my colours, Install) are
staged like any change and written by the save, never over an existing file.
"""

from __future__ import annotations

import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import tomlkit

THEMES_DIR = Path.home() / ".config" / "alacritty" / "themes"
LOCK_MARKS = ("do not edit", "generated by")
COLOUR_RE = re.compile(r"#[0-9a-fA-F]{6}")

# the colours a theme is made of, in the order people think of them
NAMES = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
PRIMARY = [("primary.background", "Background"), ("primary.foreground", "Text"),
           ("cursor.cursor", "Cursor"), ("cursor.text", "Text under the cursor"),
           ("selection.background", "Selection"), ("selection.text", "Selected text")]
PALETTE = [(f"normal.{n}", f"{n.capitalize()}") for n in NAMES] + \
          [(f"bright.{n}", f"Bright {n}") for n in NAMES]

# Catppuccin Mocha, offered in the colour list next to the theme's own
CATPPUCCIN = [("Base", "#1e1e2e"), ("Mantle", "#181825"), ("Crust", "#11111b"), ("Surface 0", "#313244"),
              ("Surface 1", "#45475a"), ("Surface 2", "#585b70"), ("Overlay", "#6c7086"),
              ("Subtext", "#a6adc8"), ("Text", "#cdd6f4"), ("Rosewater", "#f5e0dc"), ("Pink", "#f5c2e7"),
              ("Mauve", "#cba6f7"), ("Red", "#f38ba8"), ("Peach", "#fab387"), ("Yellow", "#f9e2af"),
              ("Green", "#a6e3a1"), ("Teal", "#94e2d5"), ("Sky", "#89dceb"), ("Blue", "#89b4fa"),
              ("Lavender", "#b4befe")]

# Alacritty's own colours, when nothing sets them
DEFAULTS = {"primary.background": "#181818", "primary.foreground": "#d8d8d8",
            "normal.black": "#181818", "normal.red": "#ac4242", "normal.green": "#90a959",
            "normal.yellow": "#f4bf75", "normal.blue": "#6a9fb5", "normal.magenta": "#aa759f",
            "normal.cyan": "#75b5aa", "normal.white": "#d8d8d8", "bright.black": "#6b6b6b",
            "bright.red": "#c55555", "bright.green": "#aac474", "bright.yellow": "#feca88",
            "bright.blue": "#82b8c8", "bright.magenta": "#c28cb8", "bright.cyan": "#93d3c3",
            "bright.white": "#f8f8f8"}


@dataclass
class Theme:
    name: str
    path: Path | None                 # None: the settings file's own colours
    colours: dict = field(default_factory=dict)   # the [colors] table, plain
    locked_by: str = ""               # "hypeForge" when another tool maintains it
    error: str = ""                   # why it can't be read
    pending: bool = False             # staged, not written yet

    @property
    def locked(self) -> bool:
        return bool(self.locked_by)

    def colour(self, key: str) -> str | None:
        """'primary.background' → '#1a1a1a'; None when the theme doesn't set it."""
        node: Any = self.colours
        for part in key.split("."):
            if not isinstance(node, dict) or part not in node:
                return None
            node = node[part]
        return node if isinstance(node, str) and COLOUR_RE.fullmatch(node) else None

    def shown(self, key: str) -> str:
        """The colour as drawn: the theme's, or Alacritty's own when unset."""
        return self.colour(key) or DEFAULTS.get(key, "#d8d8d8")


def _locked_by(text: str) -> str:
    head = "\n".join(text.splitlines()[:5]).lower()
    if not any(m in head for m in LOCK_MARKS):
        return ""
    m = re.search(r"generated by ([\w.-]+)", head)
    return m.group(1).replace("hypeforge", "hypeForge") if m else "another tool"


def read_theme(path: Path) -> Theme:
    try:
        text = path.read_text(encoding="utf-8")
        data = tomllib.loads(text)
    except (OSError, tomllib.TOMLDecodeError) as e:
        return Theme(path.stem, path, error=str(e).splitlines()[0] if str(e) else "can't be read")
    colours = data.get("colors", {}) if isinstance(data.get("colors"), dict) else {}
    if not colours:
        return Theme(path.stem, path, locked_by=_locked_by(text), error="has no colours")
    return Theme(path.stem, path, colours=colours, locked_by=_locked_by(text))


def list_themes(themes_dir: Path = THEMES_DIR) -> list[Theme]:
    if not themes_dir.is_dir():
        return []
    return [read_theme(p) for p in sorted(themes_dir.glob("*.toml"), key=lambda p: p.stem.lower())]


def import_path(path: Path) -> str:
    """How the settings file names a theme: ~/… when it is under home."""
    home = str(Path.home())
    s = str(path)
    return "~" + s[len(home):] if s.startswith(home + "/") else s


def _expand(p: str, base: Path) -> Path:
    p = str(p)
    if p.startswith("~/"):
        return Path.home() / p[2:]
    q = Path(p)
    return q if q.is_absolute() else base.parent / q


def active_theme(session, themes_dir: Path = THEMES_DIR) -> Path | None:
    """The theme file in use: the first import that lives in the themes folder."""
    for p in session.value("general.import") or []:
        full = _expand(p, session.path)
        if themes_dir in full.parents or full.parent == themes_dir:
            return full
    return None


def own_colours(session) -> dict:
    c = session.file.get("colors")
    return c if isinstance(c, dict) else {}


def use_changes(session, theme_path: Path, themes_dir: Path = THEMES_DIR) -> dict[str, Any]:
    """The changes that make ``theme_path`` the theme: first in the imports,
    other themes out of them, the settings file's own colours out."""
    from .settings_file import REMOVE
    keep = [p for p in (session.value("general.import") or [])
            if not (themes_dir in _expand(p, session.path).parents)]
    out: dict[str, Any] = {"general.import": [import_path(theme_path)] + keep}
    if own_colours(session):
        out["colors"] = REMOVE
    return out


def theme_text(colours: dict, made_from: str = "") -> str:
    """A theme file holding only ``[colors]``."""
    doc = tomlkit.document()
    doc.add(tomlkit.comment(f"Made with alacrittyForge{f' from {made_from}' if made_from else ''}."))
    doc.add(tomlkit.nl())
    doc["colors"] = colours
    out = tomlkit.dumps(doc)
    tomllib.loads(out)
    return out


def free_name(base: str, themes_dir: Path = THEMES_DIR, taken: set[str] = frozenset()) -> str:
    """'KognogOS-theme (mine)', then '… (mine 2)': never an existing file."""
    name = f"{base} (mine)"
    n = 2
    while (themes_dir / f"{name}.toml").exists() or name in taken:
        name = f"{base} (mine {n})"
        n += 1
    return name


def safe_file_name(name: str) -> str:
    """A theme name as a file name: letters, digits, space, ( ) . _ - only."""
    cleaned = re.sub(r"[^\w ().-]", "", name).strip(" .")
    return cleaned or "theme"


def check_install(path: Path) -> str:
    """Why a file can't be installed as a theme; "" when it can."""
    if path.suffix != ".toml":
        return "a theme is a .toml file"
    try:
        if path.stat().st_size > 256 * 1024:
            return "too big for a theme"
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError) as e:
        return f"can't be read ({str(e).splitlines()[0] if str(e) else 'not valid TOML'})"
    if not isinstance(data.get("colors"), dict) or not data["colors"]:
        return "has no colours, so it isn't a theme"
    extra = [k for k in data if k != "colors"]
    if extra:
        return f"changes more than colours ({', '.join(extra)}); only colour themes are installed"
    return ""
